INSERT INTO children (user_id, name, avatar_url) VALUES (1, 'Olivia', 'https://w7.pngwing.com/pngs/340/849/png-transparent-child-avatar-girl-woman-computer-icons-child-face-hand-people.png');
INSERT INTO children (user_id, name, avatar_url) VALUES (1, 'Emma', 'https://e7.pngegg.com/pngimages/399/274/png-clipart-child-computer-icons-avatar-user-profile-girl-illustration-child-hand.png');
INSERT INTO children (user_id, name, avatar_url) VALUES (1, 'Ava', 'https://img.favpng.com/18/15/19/child-computer-icons-avatar-nike-dunk-png-favpng-pLr1UjmfU16miDep2EH4T6eRZ.jpg');
INSERT INTO children (user_id, name, avatar_url) VALUES (1, 'Charlotte', 'https://img.favpng.com/7/6/7/child-computer-icons-avatar-png-favpng-HHHh9g1G2yrzce5PQrAT3uv0C.jpg');
INSERT INTO children (user_id, name, avatar_url) VALUES (1, 'Oliver', 'https://img.favpng.com/1/10/3/computer-icons-child-avatar-png-favpng-1KY4gtPN1Fab6LrVpVM8AjtnH.jpg');
INSERT INTO children (user_id, name, avatar_url) VALUES (2, 'Charlotte', 'https://img.favpng.com/7/6/7/child-computer-icons-avatar-png-favpng-HHHh9g1G2yrzce5PQrAT3uv0C.jpg');
INSERT INTO children (user_id, name, avatar_url) VALUES (2, 'Oliver', 'https://img.favpng.com/1/10/3/computer-icons-child-avatar-png-favpng-1KY4gtPN1Fab6LrVpVM8AjtnH.jpg');
INSERT INTO children (user_id, name, avatar_url) VALUES (3, 'Charlotte', 'https://img.favpng.com/7/6/7/child-computer-icons-avatar-png-favpng-HHHh9g1G2yrzce5PQrAT3uv0C.jpg');
INSERT INTO children (user_id, name, avatar_url) VALUES (3, 'Oliver', 'https://img.favpng.com/1/10/3/computer-icons-child-avatar-png-favpng-1KY4gtPN1Fab6LrVpVM8AjtnH.jpg');
